[package]
name = "pwner"
edition = "2018"
version = "0.1.0"
authors = ["Marcelo Lima <marcelowind@gmail.com>"]
readme = "README.md"
keywords = ["process", "pipe", "async", "tokio"]
repository = "https://github.com/m-lima/powner"
categories = ["asynchronous", "concurrency"]
description = "A wrapper around child processes providing facilities for sync and async read and write"
license-file = "LICENSE"

[features]
default = []
async = [ "tokio" ]

[dependencies]
tokio = { version = "0.2", features = [ "io-std", "io-util", "macros", "process", "rt-core", "sync", "time" ], optional = true }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.17" }
